GHM.Website.ThaiThinhMedic/Controllers/ImageHandlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace GHM.Website.ThaiThinhMedic.Controllers
{
    public class ImageHandlerController : Controller
    {
        // GET: /<controller>/
        //public ActionResult Index(string url, int? width, int? height, int? type)
        //{
        //    if (string.IsNullOrEmpty(url))
        //    {
                //                using (var fileStream = new FileStream(Server.MapPath(@"/assets/images/no-image.png"), FileMode.Open, FileAccess.Read))
                //                {
                //                    Image orginImage = Image.FromStream(fileStream);
                //                    int newWidth = width ?? orginImage.Width;
                //                    int newHeight = height ?? orginImage.Height;
                //                    Image image = Common.ResizeImage(newWidth, newHeight, fileStream, type ?? (int)ImageType.Jpg);

                //                    //int newWidth = width ?? fileStream.;
                //                    //int newHeight = height ?? 70;

                //                    //Image image = Common.ResizeImage(newWidth, newHeight, fileStream, type ?? (int)ImageType.Jpg);

                //                    using (var stream = new MemoryStream())
                //                    {
                //                        if (type == (int)ImageType.Png)
                //                            image.Save(stream, ImageFormat.Png);
                //                        else
                //                            image.Save(stream, ImageFormat.Jpeg);

                //                        return File(stream.ToArray(), System.Net.Mime.MediaTypeNames.Application.Octet);
                //                    }
                //                }
                //            }
                //            var adminUrl = ConfigurationManager.AppSettings["adminPath"];
                //            var path = $"{adminUrl}{url}";
                //            try
                //            {
                //                using (var fileStream = new FileStream(path, FileMode.Open, FileAccess.Read))
                //                {
                //                    Image orginImage = Image.FromStream(fileStream);
                //                    int newWidth = width ?? orginImage.Width;
                //                    int newHeight = height ?? orginImage.Height;
                //                    Image image = Common.ResizeImage(newWidth, newHeight, fileStream, type ?? (int)ImageType.Jpg);

                //                    using (var stream = new MemoryStream())
                //                    {
                //                        if (type == (int)ImageType.Png)
                //                            image.Save(stream, ImageFormat.Png);
                //                        else
                //                            image.Save(stream, ImageFormat.Jpeg);

                //                        return File(stream.ToArray(), System.Net.Mime.MediaTypeNames.Application.Octet);
                //                    }
                //                }
                //            }
                //#pragma warning disable CS0168 // The variable 'ex' is declared but never used
                //            catch (Exception ex)
                //#pragma warning restore CS0168 // The variable 'ex' is declared but never used
                //            {
                //                return null;
                //            }

        //        return View();

        //    }
        //}
    }
}

GHM.Website.ThaiThinhMedic/Views/Shared/_FacultySlider.cshtml
@*@using Clinic.Business.Complex.Website
    @{
        var specialist = ViewBag.ListSpecialist as List<SpecialistResult>;
    }

    <div id="facultySlider">
        @foreach (var item in specialist)
        {
            <div class="item">
                <img class="lazy" data-src="@Url.Action("Index", "ImageHandler", new { url = item.Image, width = 270, height = 270}) " />
                <a href="@string.Format("/{0}.html", item.SeoLink)" class="wrapper-info">
                    <div class="name">@item.Title</div>
                    <div class="description">@item.Description</div>
                </a>
            </div>
        }
    </div>*@

<div id="facultySlider">
    @{for (int i = 0; i <= 10; i++)
        {
            <div class="item">
                <img class="lazy" src="~/assets/images/chuyenkhoa.jpg" width="270" height="270" />
                <a href="javascript://" class="wrapper-info">
                    <div class="name">KHoa</div>
                    <div class="description">Khoa</div>
                </a>
            </div>
        }
    }
</div>

GHM.Website.ThaiThinhMedic/Views/Shared/_Footer.cshtml
<div class="wrapper-footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <h4 class="title">
                    <i class="fa fa-home"></i>
                    Phòng khám đa khoa 125 Thái Thịnh
                </h4>
                <ul>
                    <li>
                        <i class="fa fa-map-marker"></i>
                        Địa chỉ: 125 - 127 Thái Thịnh - Đống Đa - Hà Nội
                    </li>
                    <li>
                        <i class="fa fa-clock-o"></i>
                        Giờ làm việc: Từ 7:30 - 20:00
                    </li>
                    <li>
                        <i class="fa fa-volume-control-phone"></i>
                        Hotline: 0972 88 11 25
                    </li>
                    <li>
                        <i class="fa fa-envelope-o"></i>
                        Email: info@pkdktt.com
                    </li>
                </ul>
                <h4 class="title cm-mgb-20">
                    <i class="fa fa-phone-square"></i>
                    Tổng đài chăm sóc khách hàng:
                    <br />
                    <b style="font-size: 30px; margin-top:15px; display: block; padding-left: 20px;">0243.853.5522</b>
                    <b style="font-size: 30px; margin-top:15px; display: block; padding-left: 20px;">0247.309.6888</b>
                </h4>
                <div class="cm-pdl-20">
                    <a href="/lien-he" class="btn btn-success btn-lg">
                        Gửi tin nhắn
                    </a>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="fb-page" data-href="https://www.facebook.com/phongkhamdakhoa125thaithinh/" data-tabs="timeline" data-height="350" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
                    <blockquote cite="https://www.facebook.com/phongkhamdakhoa125thaithinh/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/phongkhamdakhoa125thaithinh/">Phòng khám 125 Thái Thịnh</a></blockquote>
                </div>
            </div>
            <div class="col-sm-5">
                <iframe frameborder="0" width="100%" height="350" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=125%20thai%20thinh&key=AIzaSyAWPEgy1UOyTEXbUsU_9GE2O3yhBj4w7es" allowfullscreen></iframe>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-sm-12">
                @*<h4 class="title">
                        <i class="fa fa-user-md"></i>
                        Chuyên khoa của chúng tôi
                    </h4>*@
                <ul class="list-specialist cm-mgb-0 center">
                    <li><a href="~/chuyen-khoa/khoa-da-lieu.html" title="Khoa Da Liễu" data-toggle="tooltip" data-placement="top"><img class="lazy" src="/assets/images/13-Chuyen-Khoa/dalieu.png" alt="Khoa Da Liễu" /></a></li>
                    <li><a href="~/chuyen-khoa/khoa-dien-nao--luu-huyet-nao.html" title="Khoa Điện não" data-toggle="tooltip" data-placement="top"><img class="lazy" src="/assets/images/13-Chuyen-Khoa/diennao.png" alt="Khoa Điện Não" /></a></li>
                    <li><a href="~/chuyen-khoa/khoa-mat.html" title="Khoa Mắt" data-toggle="tooltip" data-placement="top"><img class="lazy" src="/assets/images/13-Chuyen-Khoa/mat.png" alt="Khoa Mắt" /></a></li>
                    <li><a href="~/chuyen-khoa/khoa-ngoai.html" title="Khoa Ngoại" data-toggle="tooltip" data-placement="top"><img class="lazy" src="/assets/images/13-Chuyen-Khoa/ngoai.png" alt="Khoa Ngoại" /></a></li>
                    <li><a href="~/chuyen-khoa/nhi-khoa.html" title="Khoa Nhi" data-toggle="tooltip" data-placement="top"><img class="lazy" src="/assets/images/13-Chuyen-Khoa/nhi.png" alt="Khoa Nhi" /></a></li>
                    <li><a href="~/chuyen-khoa/noi-tong-quat.html" title="Khoa Nội" data-toggle="tooltip" data-placement="top"><img class="lazy" src="/assets/images/13-Chuyen-Khoa/noi.png" alt="Khoa Nội" /></a></li>
                    <li><a href="~/chuyen-khoa/noi-soi-tieu-hoa.html" title="Khoa Nội soi" data-toggle="tooltip" data-placement="top"><img class="lazy" src="/assets/images/13-Chuyen-Khoa/noisoi.png" alt="Khoa Nội soi" /></a></li>
                    <li><a href="~/chuyen-khoa/khoa-rang--ham--mat.html" title="Khoa Răng Hàm Mặt" data-toggle="tooltip" data-placement="top"><img class="lazy" src="/assets/images/13-Chuyen-Khoa/rhm.png" alt="Khoa Răng Hàm Mặt" /></a></li>
                    <li><a href="~/chuyen-khoa/san-phu-khoa.html" title="Khoa Sản" data-toggle="tooltip" data-placement="top"><img class="lazy" src="/assets/images/13-Chuyen-Khoa/san.png" alt="Khoa Sản" /></a></li>
                    <li><a href="~/chuyen-khoa/trung-tam-sieu-am.html" title="Khoa Siêu âm" data-toggle="tooltip" data-placement="top"><img class="lazy" src="/assets/images/13-Chuyen-Khoa/sieuam.png" alt="Khoa Siêu âm" /></a></li>
                    <li><a href="~/chuyen-khoa/khoa-tai--mui--hong.html" title="Khoa Tai Mũi Họng" data-toggle="tooltip" data-placement="top"><img class="lazy" src="/assets/images/13-Chuyen-Khoa/tmh.png" alt="Khoa Tai Mũi Họng" /></a></li>
                    <li><a href="~/chuyen-khoa/trung-tam-xet-nghiem.html" title="Khoa Xét Nghiệm" data-toggle="tooltip" data-placement="top"><img class="lazy" src="/assets/images/13-Chuyen-Khoa/xnghiem.png" alt="Khoa Xét Nghiệm" /></a></li>
                    <li><a href="~/chuyen-khoa/phong-x-quang.html" title="Khoa X-Quang" data-toggle="tooltip" data-placement="top"><img class="lazy" src="/assets/images/13-Chuyen-Khoa/xray.png" alt="Khoa X-Quang" /></a></li>
                </ul>
            </div>
        </div>
        <hr />
        <div class="copy-right">
            Bản quyền thuộc về © 2017 Công ty cổ phần Bệnh viện Thái Thịnh.
        </div>
    </div>
</div><!-- end wrapper-footer -->

GHM.Website.ThaiThinhMedic/Views/Shared/_Header.cshtml
@using GHM.Website.ThaiThinhMedic.Infrastructure.Models
@using System.Text
@using Microsoft.AspNetCore.Html
@{
    var listMenuItem = ViewBag.MainNav as List<MenuItem>;
}

<nav class="navbar navbar-default">
    <div class="navbar-header">
        <div class="container">
            <div class="row">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#clinicMainNav" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand clinic-logo" href="/">
                    <img src="~/assets/images/logo-full.png" alt="công ty cổ phần bệnh viện thái thịnh" />
                </a>
                <ul class="list-inline list-unstyled pull-right visible-lg">
                    <li><a href="https://www.facebook.com/phongkhamdakhoa125thaithinh/" target="_blank"><i class="fa fa-facebook-square"></i></a></li>
                    <li><a href="/" target="_blank"><i class="fa fa-youtube-play"></i></a></li>
                    <li><a href="/" target="_blank"><i class="fa fa-phone-square"></i></a></li>
                    <li><span>0243 853 5522 / 0247 309 6888</span></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="collapse navbar-collapse" id="clinicMainNav">
        <div class="col-sm-12 menu">
            <div class="container">
                <!-- Collect the nav links, forms, and other content for toggling -->
                <ul class="nav navbar-nav">
                    <li class=""><a href="/" class="transition">Trang chủ <span class="sr-only">(current)</span></a></li>
                    <li class="dropdown">
                        <a href="http://clinic.com/appointmentschedule/fullcalendar#">Giới thiệu</a>
                        <ul>
                            <li><a href="#">Thư ngỏ của Ban Giám Đốc</a></li>
                            <li>
                                <a href="#">
                                    Về chúng tôi
                                    <i class="fa fa-angle-right"></i>
                                </a>
                                <ul>
                                    <li><a href="#">Lịch sử bệnh viện thái thịnh</a></li>
                                    <li><a href="#">Sơ đồ tổ chức</a></li>
                                    <li><a href="#">Cơ sở vật chất - Trang thiết bị</a></li>
                                    <li><a href="#">Đội ngũ chuyên gia</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="/cac-chuyen-khoa">Chuyên khoa</a>
                        <ul>
                            <li><a href="#">Khoa nội</a></li>
                            <li><a href="#">Khoa siêu âm</a></li>
                            <li><a href="#">Trung tâm xét nghiệm</a></li>
                            <li><a href="#">Khoa nhi</a></li>
                            <li><a href="#">Sản phụ khoa</a></li>
                            <li><a href="#">Khoa da liễu</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="/dich-vu-ho-tro">Dịch vụ hỗ trợ</a>
                        <ul>
                            <li>
                                <a href="#">
                                    Dịch vụ chọn gói
                                    <i class="fa fa-angle-right"></i>
                                </a>
                                <ul>
                                    <li><a href="#">Gói khám sức khoẻ định kỳ</a></li>
                                    <li><a href="#">Chăm sóc thai kỳ trọn gói</a></li>
                                    <li><a href="#">Gói khám sức khoẻ tiền hôn nhân</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#">
                                    Dịch vụ bảo hiểm
                                    <i class="fa fa-angle-right"></i>
                                </a>
                                <ul>
                                    <li><a href="#">Bảo hiểm BIC</a></li>
                                    <li><a href="#">Bảo hiểm PVI</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="/thong-tin-suc-khoe">Tin tức</a>
                        <ul>
                            <li><a href="#">Góc chuyên môn</a></li>
                            <li><a href="#">Tin hoạt động</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="/dat-hen">Tuyển dụng</a>
                        <ul>
                            <li><a href="#">Chính sách nhân sự</a></li>
                            <li><a href="#">Thông tin tuyển dụng</a></li>
                            <li><a href="#">Đơn ứng tuyển</a></li>
                        </ul>
                    </li>
                    <li><a href="/lien-he">Liên hệ</a></li>
                    @*@if (CurrentPatient != null)
                        {*@
                    <li class="dropdown">
                        <a href="javascript://" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Tài khoản <span class="caret"></span></a>
                        <ul>
                            <li>
                                <a href="/">
                                    <i class="fa fa-user cm-mgr-10"></i>
                                    Thông tin tài khoản
                                </a>
                            </li>
                            <li>
                                <a href="/">
                                    <i class="fa fa-history cm-mgr-10"></i>
                                    Lịch sử khám
                                </a>
                            </li>
                            <li>
                                <a href="/xem-video">
                                    <i class="fa fa-video-camera cm-mgr-10"></i>
                                    Video siêu âm
                                </a>
                            </li>
                            <li>
                                <a href="/xem-anh">
                                    <i class="fa fa-file-picture-o cm-mgr-10"></i>
                                    Ảnh siêu âm
                                </a>
                            </li>
                            <li>
                                <a href="/dang-xuat">
                                    <i class="fa fa-sign-out cm-mgr-10"></i>
                                    Đăng xuất
                                </a>
                            </li>
                        </ul>
                    </li>
                    @* }
                        else
                        {
                        <li><a href="/dang-nhap">Đăng nhập</a></li>
                        }*@
                </ul>
            </div>
        </div>
    </div>
</nav>

GHM.Website.ThaiThinhMedic/Views/Shared/_Layout.cshtml
@using Newtonsoft.Json
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="content-language" content="vietnamese">
    <title>@(string.IsNullOrEmpty(ViewBag.Title) ? "Phòng khám 125 Thái Thịnh - 20 năm phát triển" : ViewBag.Title)</title>
    <link rel="apple-touch-icon" sizes="76x76" href="/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png">
    <link rel="icon" type="image/png" size="48x48" href="/favicons/favicon.ico">
    <link rel="manifest" href="/favicons/manifest.json">
    <link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">
    <meta name="keywords" content="@(string.IsNullOrEmpty(ViewBag.Keyword) ? "Công ty cổ phần bệnh viện thái thịnh" : ViewBag.Keyword)">
    <meta name="description" content="@(string.IsNullOrEmpty(ViewBag.Description) ? Html.Raw("Với phương châm &#34;Luôn ân cần – Luôn cố gắng&#34;, trải qua 20 năm hoạt động, Phòng khám là địa chỉ uy tín trong lĩnh vực chăm sóc sức khỏe mà người dân Hà Nội và các tỉnh lân cận &#34;chọn mặt gửi vàng&#34;.") : Html.Raw(ViewBag.Description))" />
    @*<meta property="url" content="@Html.Raw(Request.Url)" />*@
    <meta property="type" content="website" />
    <meta property="title" content="@Html.Raw(ViewBag.Title)" />
    <meta property="description" content="@(string.IsNullOrEmpty(ViewBag.Description) ? Html.Raw("Với phương châm &#34;Luôn ân cần – Luôn cố gắng&#34;, trải qua 20 năm hoạt động, Phòng khám là địa chỉ uy tín trong lĩnh vực chăm sóc sức khỏe mà người dân Hà Nội và các tỉnh lân cận &#34;chọn mặt gửi vàng&#34;.") : Html.Raw(ViewBag.Description))" />
    <meta property="image" content="@(string.IsNullOrEmpty(ViewBag.Image) ? "/assets/images/logo-full-temp.png" : ViewBag.Image)" />
    @*<meta property="og:url" content="@Html.Raw(Request.Url)" />*@
    <meta property="og:type" content="website" />
    <meta property="og:title" content="@Html.Raw(ViewBag.Title)" />
    <meta property="og:description" content="@(string.IsNullOrEmpty(ViewBag.Description) ? Html.Raw("Với phương châm &#34;Luôn ân cần – Luôn cố gắng&#34;, trải qua 20 năm hoạt động, Phòng khám là địa chỉ uy tín trong lĩnh vực chăm sóc sức khỏe mà người dân Hà Nội và các tỉnh lân cận &#34;chọn mặt gửi vàng&#34;.") : Html.Raw(ViewBag.Description))" />
    <meta property="og:image" content="@(string.IsNullOrEmpty(ViewBag.Image) ? "/assets/images/logo-full-temp.png" : ViewBag.Image)" />
    <link href="~/assets/images/favicon.ico" rel="shortcut icon" type="image/x-icon">
    @*Css*@
    <link href="~/assets/plugins/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/assets/plugins/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/plugins/owl.carousel/owl-carousel/owl.carousel.css" rel="stylesheet" />
    <link href="~/assets/plugins/owl.carousel/owl-carousel/owl.theme.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/less/main.min.css" rel="stylesheet" />
    <link href="~/Content/less/header.min.css" rel="stylesheet" />

    @*<environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>*@
</head>
<body class="bg_grey">
    <div id="fb-root"></div>
    @Html.AntiForgeryToken()
    @{Html.RenderPartial("_Header");}
    <div class="body-content">
        @RenderBody()
    </div>
    <a href="javascript://" id="backToTop" class="">
        <i class="fa fa-angle-up fa-2x"></i>
    </a>
    <div class="hotline">
        <a href="tel:02438535522" class="content">
            <img src="~/assets/images/Utils/Call-06.png" class="img-responsive" alt="" />
        </a>
    </div>
    @{Html.RenderPartial("_Footer");}
    @*<environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>*@
    @*Script*@
    <script src="~/assets/plugins/jquery/jquery-1.10.2.min.js"></script>
    <script src="~/assets/plugins/knockout/knockout-latest.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    @*/bundles/app*@
    <script src="~/Scripts/jquery.lazy-master/jquery.lazy.min.js"></script>
    <script src="~/built/app.js"></script>
    <script>
        @*var currentPatient = @Html.Raw(JsonConvert.SerializeObject(CurrentPatient, Common.GetCalmcaseSetting()));*@
        var currentPatient = "";
    </script>
    <script src="~/Scripts/player/jwplayer.js"></script>
    <script type="text/javascript">jwplayer.key = "5qMQ1qMprX8KZ79H695ZPnH4X4zDHiI0rCXt1g==";</script>
    @RenderSection("knockout", required: false)
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-110941107-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-110941107-1');
    </script>
    <div id="fb-root"></div>
    @RenderSection("Scripts", required: false)
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.11&appId=432544803543466';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
    <script type='text/javascript'>window._sbzq || function (e) { e._sbzq = []; var t = e._sbzq; t.push(["_setAccount", 16418]); var n = e.location.protocol == "https:" ? "https:" : "http:"; var r = document.createElement("script"); r.type = "text/javascript"; r.async = true; r.src = n + "//static.subiz.com/public/js/loader.js"; var i = document.getElementsByTagName("script")[0]; i.parentNode.insertBefore(r, i) }(window);</script>
</body>
</html>

GHM.Website.ThaiThinhMedic/Views/Shared/_MainSlider.cshtml
@*@using Clinic.Business.Complex.Website
    @{
        var mainSlider = ViewBag.MainSlider as List<SliderSearchResult>;
    }

    @if (mainSlider != null && mainSlider.Any())
    {
        <div id="mainSlider" class="owl-carousel owl-theme">
            @foreach (var item in mainSlider)
            {
                <div class="item">
                    <a href="@string.Format("{0}", string.IsNullOrEmpty(item.Url) ? "javascript://" : item.Url)">
                        <img src="@Url.Action("Index", "ImageHandler", new { url = item.ImageUrl, width = 1920, height = 768, type = 1 })" alt="@string.Format("{0}", string.IsNullOrEmpty(item.Name) ? "" : item.Name)">
                    </a>
                </div>
            }
        </div>
    }*@

<div id="mainSlider" class="owl-carousel owl-theme">
    <div class="item">
        <a href="javascript://">
            <img src="~/assets/images/Home_Index/slide/banner1.jpg" />
        </a>
    </div>
    <div class="item">
        <a href="javascript://">
            <img src="~/assets/images/Home_Index/slide/banner2.jpg" />
        </a>
    </div>
    <div class="item">
        <a href="javascript://">
            <img src="~/assets/images/Home_Index/slide/banner3.jpg" />
        </a>
    </div>
</div>